# Generated by Django 4.2 on 2025-09-02 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, null=True, verbose_name='Date of Passing')),
                ('bio', models.TextField(blank=True, help_text='Biography or description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='memorial_covers/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('donations_count', models.IntegerField(default=0)),
                ('trees_planted_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField(blank=True, help_text='Text content for text memories')),
                ('image', models.ImageField(blank=True, null=True, upload_to='memory_images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='main_app.memorial')),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='memorial',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='main_app.userprofile'),
        ),
    ]
